<?php

/**
 * @file
 * Subscriptions module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\oe_subscriptions\Form\SettingsForm;

/**
 * Implements hook_theme().
 */
function oe_subscriptions_theme($existing, $type, $theme, $path) {
  return [
    'oe_subscriptions_no_subscriptions' => [
      'variables' => [],
    ],
    'oe_subscriptions_introduction' => [
      'variables' => [
        'text' => '',
      ],
    ],
    'oe_subscriptions_user_subscriptions_page' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for the user subscriptions page template.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content of the page.
 */
function template_preprocess_oe_subscriptions_user_subscriptions_page(&$variables): void {
  $subscriptions_config = \Drupal::configFactory()->get(SettingsForm::CONFIG_NAME);
  $introduction_text = $subscriptions_config->get('introduction_text');

  if (empty($introduction_text['value'])) {
    return;
  }

  $variables['introduction'] = [
    '#type' => 'processed_text',
    '#text' => $introduction_text['value'],
    '#format' => $introduction_text['format'] ?? '',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for the user subscriptions form.
 *
 * Wraps the user subscriptions form with the dedicated page template.
 * This is added in a hook so the standard form wrappers will be added normally,
 * and our wrapper only appended later on.
 */
function oe_subscriptions_form_oe_subscriptions_user_subscriptions_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#theme_wrappers']['oe_subscriptions_user_subscriptions_page'] = [
    '#attributes' => [],
  ];
}

/**
 * Implements hook_flag_insert().
 */
function oe_subscriptions_flag_insert(EntityInterface $entity) {
  $flag_prefix = \Drupal::config('message_subscribe.settings')->get('flag_prefix');
  if (strpos($entity->id(), $flag_prefix . '_') == 0) {
    $mail_prefix = \Drupal::config('message_subscribe_email.settings')->get('flag_prefix');
    $email_flag_id = str_replace($flag_prefix, $mail_prefix, $entity->id());
    if (Drupal::service('entity_type.manager')->getStorage('flag')->load($email_flag_id)) {
      return;
    }
    $entity->createDuplicate()
      ->set('id', $email_flag_id)
      ->set('label', $mail_prefix . ' - ' . $entity->label())
      ->save();
  }
}

/**
 * Implements hook_flag_delete().
 */
function oe_subscriptions_flag_delete(EntityInterface $entity) {
  $flag_prefix = \Drupal::config('message_subscribe.settings')->get('flag_prefix');
  if (strpos($entity->id(), $flag_prefix . '_') == 0) {
    $mail_prefix = \Drupal::config('message_subscribe_email.settings')->get('flag_prefix');
    $email_flag_id = str_replace($flag_prefix, $mail_prefix, $entity->id());
    if ($email_flag = \Drupal::service('entity_type.manager')->getStorage('flag')->load($email_flag_id)) {
      $email_flag->delete();
    }
  }
}
