<?php

/**
 * @file
 * Subscriptions module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_insert().
 */
function oe_subscriptions_flag_insert(EntityInterface $entity) {
  $mail_prefix = \Drupal::config('message_subscribe_email.settings')->get('flag_prefix');
  if (empty($mail_prefix) || !str_starts_with($entity->id(), 'subscribe_')) {
    return;
  }
  $email_flag_id = str_replace('subscribe_', $mail_prefix . '_', $entity->id());
  if (Drupal::service('entity_type.manager')->getStorage('flag')->load($email_flag_id)) {
    return;
  }
  $entity->createDuplicate()
    ->set('id', $email_flag_id)
    ->set('label', $mail_prefix . ' - ' . $entity->label())
    ->save();
}

/**
 * Implements hook_ENTITY_insert().
 */
function oe_subscriptions_flag_delete(EntityInterface $entity) {
  $mail_prefix = \Drupal::config('message_subscribe_email.settings')->get('flag_prefix');
  if (empty($mail_prefix) || !str_starts_with($entity->id(), 'subscribe_')) {
    return;
  }
  $email_flag_id = str_replace('subscribe_', $mail_prefix . '_', $entity->id());
  if ($email_flag = \Drupal::service('entity_type.manager')->getStorage('flag')->load($email_flag_id)) {
    $email_flag->delete();
  }
}
