oe_subscriptions.settings:
  type: config_object
  label: 'Terms page'
  mapping:
    terms_url:
      type: text
      label: 'Page link'
    introduction_text:
      type: text_format
      label: 'Subscriptions page text'
