<?php

/**
 * @file
 * Anonymous subscriptions module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Mail\MailFormatHelper;

/**
 * Implements hook_ENTITY_insert().
 */
function oe_subscriptions_anonymous_flag_insert(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Implements hook_ENTITY_update().
 */
function oe_subscriptions_anonymous_flag_update(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Implements hook_ENTITY_delete().
 */
function oe_subscriptions_anonymous_flag_delete(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Helper function to flush extra field cache().
 */
function _oe_subscriptions_anonymous_flush_extra_field(EntityInterface $entity) {
  if (str_starts_with($entity->id(), 'subscribe_')) {
    \Drupal::service('plugin.manager.extra_field_display')->clearCachedDefinitions();
  }
}

/**
 * Implements hook_mail().
 */
function oe_subscriptions_anonymous_mail($key, &$message, $params) {
  if ($key !== 'oe_subscriptions_anonymous:subscription_create') {
    return;
  }
  // Links for subscription management.
  $variables = [
    '%entity_link' => $params['entity_link'],
    '%confirm_link' => $params['confirm_link'],
    '%cancel_link' => $params['cancel_link'],
  ];

  $body = strtr(t("Entity: %entity_link \r\n Confirm: %confirm_link \r\n Cancel: %cancel_link"), $variables);
  $message['subject'] .= t('Anonymous subscription');
  $message['body'][] = MailFormatHelper::htmlToText($body);

}
