<?php

/**
 * @file
 * Anonymous subscriptions module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\oe_subscriptions_anonymous\MailTemplate\SubscriptionCreate;
use Drupal\oe_subscriptions_anonymous\MailTemplate\UserSubscriptionsAccess;

/**
 * Implements hook_ENTITY_insert().
 */
function oe_subscriptions_anonymous_flag_insert(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Implements hook_ENTITY_update().
 */
function oe_subscriptions_anonymous_flag_update(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Implements hook_ENTITY_delete().
 */
function oe_subscriptions_anonymous_flag_delete(EntityInterface $entity) {
  _oe_subscriptions_anonymous_flush_extra_field($entity);
}

/**
 * Helper function to flush extra field cache().
 */
function _oe_subscriptions_anonymous_flush_extra_field(EntityInterface $entity) {
  if (str_starts_with($entity->id(), 'subscribe_')) {
    \Drupal::service('plugin.manager.extra_field_display')->clearCachedDefinitions();
  }
}

/**
 * Implements hook_mail().
 */
function oe_subscriptions_anonymous_mail($key, &$message, $params) {
  $class = match ($key) {
    'subscription_create' => SubscriptionCreate::class,
    'user_subscriptions_access' => UserSubscriptionsAccess::class
  };
  \Drupal::classResolver($class)->prepare($message, $params);
}

/**
 * Implements hook_theme().
 */
function oe_subscriptions_anonymous_theme($existing, $type, $theme, $path) {
  return [
    'oe_subscriptions_anonymous_message_confirm' => [
      'variables' => [],
    ],
    'oe_subscriptions_anonymous_link' => [
      'variables' => [
        'title' => '',
        'url' => '',
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for link template.
 *
 * Default template: oe-subscriptions-anonymous-link.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - link: The link text.
 *   - url: The link destination.
 *   - attributes: associative array containing the properties of the element.
 */
function template_preprocess_oe_subscriptions_anonymous_link(&$variables) {
  if (empty($variables['url'])) {
    return;
  }
  /** @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if (!$url instanceof Url) {
    return;
  }
  $variables['attributes']['href'] = $url->toString();
}
